/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.NGORegisteration;
import Business.NGO.NGO;
import Business.NGO.NGODirectory;
import Business.Person.Person;
import Business.Person.PersonDirectory;
import Business.Ecosystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.NGOOrganization;
import Business.Organization.PersonCareOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.TaskQueue.PersonCareNGOTaskRequest;
import Business.TaskQueue.PersonCareTaskRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 * Person Selection JPanel
 * @author RakshitaJ
 */
public class PersonSelectionJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Ecosystem business;
    NGO ngo;
    NGODirectory ngoDirectory;
    NGOOrganization ngoOrganization;
    String bgcstatus,financestatus;
    int uid;
    PersonDirectory personDirectory;
    PersonCareTaskRequest request;

    /**
     * Creates new form PersonSelectionJPanel
     */
    public PersonSelectionJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Ecosystem business, NGODirectory ngoDirectory, int uid, PersonDirectory personDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ngoDirectory = ngoDirectory;
        this.account = account;
        this.enterprise = enterprise;
        this.business = business;
        this.ngoOrganization = (NGOOrganization) organization;
        this.uid = uid;
        this.personDirectory = personDirectory;
        for (NGO n : ngoDirectory.getNGOList()) {
            if (n.getUsername().equals(account.getUsername())) {
                ngo = n;
                btnAdopt.setEnabled(!ngo.isFlag());
            }
        }
        populatePersonTable();
    }
    
    // PopulatePersonTable
    public void populatePersonTable() {
        DefaultTableModel dtms = (DefaultTableModel) tblPerson.getModel();
        dtms.setRowCount(0);
        for (Person person : personDirectory.getPersonList()) {
            if ("Acquired".equalsIgnoreCase(person.getStatus()) || ("Adopted by " + ngo.getName()).startsWith(person.getStatus())) {
                Object[] row = new Object[dtms.getColumnCount()];
                row[0] = person;
                row[1] = person.getPersonName();
                row[2] = person.getGender();
                row[3] = person.getPersonAge();
                row[4] = person.getStatus();
                //row[5] = child.getStatus();
                dtms.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        btnAdopt = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(134, 187, 216));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(71, 52, 58));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Person Selection");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 383, -1));

        tblPerson.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Person ID", "Person Name", "Gender", "Age", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPerson);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 790, 120));

        btnAdopt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnAdopt.setText("Adopt");
        btnAdopt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdoptActionPerformed(evt);
            }
        });
        add(btnAdopt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/My project.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 830, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdoptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdoptActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPerson.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        Person person = (Person) tblPerson.getValueAt(selectedRow, 0);
        PersonCareNGOTaskRequest personCareNGOTaskRequest = new PersonCareNGOTaskRequest();
        personCareNGOTaskRequest.setPersonID(person.getPersonID());
        personCareNGOTaskRequest.setUserID(uid);
        personCareNGOTaskRequest.setAdopterName(ngo.getName());
        personCareNGOTaskRequest.setMessage("I want to adopt");
        personCareNGOTaskRequest.setStatus("Pending with Person care");
        personCareNGOTaskRequest.setPersonName(person.getPersonName());
        personCareNGOTaskRequest.setEmailId(ngo.getEmailId());
        //adc.s
        Organization org = null;
        for (Network network : business.getNetworkCatalog()) {
            for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof PersonCareOrganization) {
                        org = organization;
                        break;
                    }
                }
            }
        }
        if (org != null) {
            org.getTaskQueue().getTaskRequestList().add(personCareNGOTaskRequest);
            account.getTaskQueue().getTaskRequestList().add(personCareNGOTaskRequest);
            business.getTaskQueue().getTaskRequestList().add(personCareNGOTaskRequest);
        }
        ngo.setFlag(true);
        JOptionPane.showMessageDialog(null, "Request has been sent to Person Care");
        btnAdopt.setEnabled(false);
    }//GEN-LAST:event_btnAdoptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdopt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPerson;
    // End of variables declaration//GEN-END:variables
}
